// One Edge TTS neural voice per language. Keep keys in sync with the
// `languages` list in client/src/components/LanguageSelector.tsx.
// Any locale not listed here falls back to DEFAULT_VOICE in routes/tts.js.
const voiceMap = {
  'vi-VN': 'vi-VN-HoaiMyNeural',       // Vietnamese (Female)
  'en-US': 'en-US-JennyNeural',        // English US (Female)
  'en-GB': 'en-GB-SoniaNeural',        // English UK (Female)
  'en-AU': 'en-AU-NatashaNeural',      // English Australia (Female)
  'ar-SA': 'ar-SA-ZariyahNeural',      // Arabic (Female)
  'bn-BD': 'bn-BD-NabanitaNeural',     // Bengali (Female)
  'zh-CN': 'zh-CN-XiaoxiaoNeural',     // Chinese Mandarin (Female)
  'zh-TW': 'zh-TW-HsiaoChenNeural',    // Chinese Traditional (Female)
  'cs-CZ': 'cs-CZ-VlastaNeural',       // Czech (Female)
  'nl-NL': 'nl-NL-ColetteNeural',      // Dutch (Female)
  'fil-PH': 'fil-PH-BlessicaNeural',   // Filipino (Female)
  'fi-FI': 'fi-FI-NooraNeural',        // Finnish (Female)
  'fr-FR': 'fr-FR-DeniseNeural',       // French (Female)
  'fr-CA': 'fr-CA-SylvieNeural',       // French Canada (Female)
  'de-DE': 'de-DE-KatjaNeural',        // German (Female)
  'el-GR': 'el-GR-AthinaNeural',       // Greek (Female)
  'he-IL': 'he-IL-HilaNeural',         // Hebrew (Female)
  'hi-IN': 'hi-IN-SwaraNeural',        // Hindi (Female)
  'hu-HU': 'hu-HU-NoemiNeural',        // Hungarian (Female)
  'id-ID': 'id-ID-GadisNeural',        // Indonesian (Female)
  'it-IT': 'it-IT-ElsaNeural',         // Italian (Female)
  'ja-JP': 'ja-JP-NanamiNeural',       // Japanese (Female)
  'ko-KR': 'ko-KR-SunHiNeural',        // Korean (Female)
  'ms-MY': 'ms-MY-YasminNeural',       // Malay (Female)
  'nb-NO': 'nb-NO-PernilleNeural',     // Norwegian (Female)
  'pl-PL': 'pl-PL-ZofiaNeural',        // Polish (Female)
  'pt-BR': 'pt-BR-FranciscaNeural',    // Portuguese Brazil (Female)
  'pt-PT': 'pt-PT-RaquelNeural',       // Portuguese Portugal (Female)
  'ro-RO': 'ro-RO-AlinaNeural',        // Romanian (Female)
  'ru-RU': 'ru-RU-SvetlanaNeural',     // Russian (Female)
  'es-ES': 'es-ES-ElviraNeural',       // Spanish Spain (Female)
  'es-MX': 'es-MX-DaliaNeural',        // Spanish Mexico (Female)
  'sv-SE': 'sv-SE-SofieNeural',        // Swedish (Female)
  'ta-IN': 'ta-IN-PallaviNeural',      // Tamil (Female)
  'th-TH': 'th-TH-PremwadeeNeural',    // Thai (Female)
  'tr-TR': 'tr-TR-EmelNeural',         // Turkish (Female)
  'uk-UA': 'uk-UA-PolinaNeural'        // Ukrainian (Female)
};

module.exports = voiceMap;
